### ISSUE TITLE
Comments on INITIUM Posts 💬

### ISSUE THREAD

**Issue by theagora** [agorahub/blog0#5]
INITIUM (muitinⒾ) Comments page https://agora0.gitlab.io/blog/initium_comments

**Comment by andyof** [comment]
> [红三代KOL兔主席的香港论述，为何在简体舆论圈走红？](https://agorahub.github.io/blog0//initium/2020/11/17/INITIUM-红三代kol兔主席的香港论述-为何在简体舆论圈走红.html)

- 花名：兔主席
- 級數：小鋼炮
- 平臺：港漂網絡
- 序列：統宣文攻專案
- 戰場：香港反送中運動
