### ISSUE TITLE
Comments on MATTERS Posts 💬

### ISSUE THREAD

**Issue by theagora** [agorahub/blog0#6]
MATTERS (srettaⓂ) Comments page https://agora0.gitlab.io/blog/matters_comments

**Comment by andyof** [comment]
> [你也落入「貨機崇拜」之中了嗎？](https://agorahub.github.io/blog0/matters/2020/11/20/MATTERS-你也落入-貨機崇拜-之中了嗎.html)

- 人類行為學：利用形式追求內容
- 社會心理學：採用形式表達意義
- 意識形態學：運用形式教化思想
